import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => ({ SANITY_STUDIO_PROJECT_ID: context.env.SANITY_STUDIO_PROJECT_ID,
    SANITY_STUDIO_DATASET: context.env.SANITY_STUDIO_DATASET,
    SANITY_STUDIO_URL: context.env.SANITY_STUDIO_URL || 'http://localhost:3333',
    SANITY_STUDIO_STEGA_ENABLED: context.env.SANITY_STUDIO_STEGA_ENABLED || false }),
});
